; Untitled, AKG format, v1.0.

; Generated by Arkos Tracker 2.

Untitled_Start
Untitled_StartDisarkGenerateExternalLabel

Untitled_DisarkByteRegionStart0
	db "AT20"
Untitled_DisarkPointerRegionStart1
	dw Untitled_ArpeggioTable	; The address of the Arpeggio table.
	dw Untitled_PitchTable	; The address of the Pitch table.
	dw Untitled_InstrumentTable	; The address of the Instrument table.
	dw Untitled_EffectBlockTable	; The address of the Effect Block table.
Untitled_DisarkPointerRegionEnd1


; The addresses of each Subsong:
Untitled_DisarkPointerRegionStart2
	dw Untitled_Subsong0_Start
Untitled_DisarkPointerRegionEnd2

; Declares all the Arpeggios.
Untitled_ArpeggioTable
Untitled_DisarkPointerRegionStart3
	dw Untitled_Arpeggio1
	dw Untitled_Arpeggio2
Untitled_DisarkPointerRegionEnd3

Untitled_Arpeggio1
	db 1	; The speed.

	db 0
	db 4
	db 0
	db -128
Untitled_DisarkWordForceReference4
	dw Untitled_Arpeggio1 + 0 + 1	; Loop.

Untitled_Arpeggio2
	db 1	; The speed.

	db 0
	db 12
	db 0
	db -128
Untitled_DisarkWordForceReference5
	dw Untitled_Arpeggio2 + 0 + 1	; Loop.

; Declares all the Pitches.
Untitled_PitchTable
Untitled_DisarkPointerRegionStart6
Untitled_DisarkPointerRegionEnd6

; Declares all the Instruments.
Untitled_InstrumentTable
Untitled_DisarkPointerRegionStart7
	dw Untitled_EmptyInstrument
	dw Untitled_Instrument1
	dw Untitled_Instrument2
	dw Untitled_Instrument3
	dw Untitled_Instrument4
	dw Untitled_Instrument5
	dw Untitled_Instrument6
	dw Untitled_Instrument7
Untitled_DisarkPointerRegionEnd7

Untitled_EmptyInstrument
	db 0	; The speed (>0, 0 for 256).
Untitled_EmptyInstrument_Loop	db 0	; No Soft no Hard. Volume: 0. Noise? false.

	db 6	; Loop to silence.

Untitled_Instrument1
	db 2	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw -15	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw -4	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw -2	; Pitch.

	db 201	; Soft only. Volume: 9. Volume only.

	db 97	; Soft only. Volume: 12.
	db 64	; Additional data. Noise: 0. Pitch? false. Arp? true. Period? false.
	db -12	; Arpeggio.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument2
	db 2	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -1	; Pitch.

	db 225	; Soft only. Volume: 12. Volume only.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

Untitled_Instrument2_Loop	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 1	; Pitch.

	db 217	; Soft only. Volume: 11. Volume only.

	db 89	; Soft only. Volume: 11.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw -2	; Pitch.

	db 7	; Loop.
Untitled_DisarkWordForceReference8
	dw Untitled_Instrument2_Loop	; Loop here.

Untitled_Instrument3
	db 5	; The speed (>0, 0 for 256).
	db 249	; Soft only. Volume: 15. Volume only.

	db 241	; Soft only. Volume: 14. Volume only.

	db 233	; Soft only. Volume: 13. Volume only.

	db 225	; Soft only. Volume: 12. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 217	; Soft only. Volume: 11. Volume only.

	db 201	; Soft only. Volume: 9. Volume only.

	db 193	; Soft only. Volume: 8. Volume only.

	db 185	; Soft only. Volume: 7. Volume only.

	db 177	; Soft only. Volume: 6. Volume only.

	db 169	; Soft only. Volume: 5. Volume only.

	db 161	; Soft only. Volume: 4. Volume only.

	db 153	; Soft only. Volume: 3. Volume only.

	db 145	; Soft only. Volume: 2. Volume only.

	db 137	; Soft only. Volume: 1. Volume only.

	db 6	; Loop to silence.

Untitled_Instrument4
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 232	; No Soft no Hard. Volume: 13. Noise? true.
	db 1	; Noise: 1.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

Untitled_Instrument5
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 34	; Additional data. Noise: 2. Pitch? true. Arp? false. Period? false.
	dw -10	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 35	; Additional data. Noise: 3. Pitch? true. Arp? false. Period? false.
	dw -30	; Pitch.

	db 216	; No Soft no Hard. Volume: 11. Noise? true.
	db 1	; Noise: 1.

	db 80	; No Soft no Hard. Volume: 10. Noise? false.

	db 208	; No Soft no Hard. Volume: 10. Noise? true.
	db 1	; Noise: 1.

	db 200	; No Soft no Hard. Volume: 9. Noise? true.
	db 1	; Noise: 1.

	db 192	; No Soft no Hard. Volume: 8. Noise? true.
	db 1	; Noise: 1.

	db 184	; No Soft no Hard. Volume: 7. Noise? true.
	db 1	; Noise: 1.

	db 176	; No Soft no Hard. Volume: 6. Noise? true.
	db 1	; Noise: 1.

	db 168	; No Soft no Hard. Volume: 5. Noise? true.
	db 1	; Noise: 1.

	db 160	; No Soft no Hard. Volume: 4. Noise? true.
	db 1	; Noise: 1.

	db 144	; No Soft no Hard. Volume: 2. Noise? true.
	db 1	; Noise: 1.

	db 136	; No Soft no Hard. Volume: 1. Noise? true.
	db 1	; Noise: 1.

	db 6	; Loop to silence.

Untitled_Instrument6
	db 1	; The speed (>0, 0 for 256).
	db 248	; No Soft no Hard. Volume: 15. Noise? true.
	db 1	; Noise: 1.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 150	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 400	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 500	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 600	; Pitch.

	db 6	; Loop to silence.

Untitled_Instrument7
	db 1	; The speed (>0, 0 for 256).
	db 121	; Soft only. Volume: 15.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 200	; Pitch.

	db 113	; Soft only. Volume: 14.
	db 32	; Additional data. Noise: 0. Pitch? true. Arp? false. Period? false.
	dw 250	; Pitch.

	db 105	; Soft only. Volume: 13.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 300	; Pitch.

	db 97	; Soft only. Volume: 12.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 350	; Pitch.

	db 89	; Soft only. Volume: 11.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 400	; Pitch.

	db 81	; Soft only. Volume: 10.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 450	; Pitch.

	db 73	; Soft only. Volume: 9.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 500	; Pitch.

	db 65	; Soft only. Volume: 8.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 550	; Pitch.

	db 57	; Soft only. Volume: 7.
	db 96	; Additional data. Noise: 0. Pitch? true. Arp? true. Period? false.
	db -12	; Arpeggio.
	dw 600	; Pitch.

	db 6	; Loop to silence.


; The indexes of the effect blocks used by this song.
Untitled_EffectBlockTable
Untitled_DisarkPointerRegionStart9
	dw Untitled_EffectBlock_P4P1	; Index 0
	dw Untitled_EffectBlock_P4P2	; Index 1
	dw Untitled_EffectBlock_P4P0	; Index 2
	dw Untitled_EffectBlock_P4P3	; Index 3
	dw Untitled_EffectBlock_P20P64P0	; Index 4
	dw Untitled_EffectBlock_P20P96P0	; Index 5
	dw Untitled_EffectBlock_P5P2P6P0	; Index 6
	dw Untitled_EffectBlock_P5P2P6P1	; Index 7
	dw Untitled_EffectBlock_P5P3P6P1	; Index 8
	dw Untitled_EffectBlock_P5P2P8	; Index 9
	dw Untitled_EffectBlock_P20P128P0	; Index 10
	dw Untitled_EffectBlock_P14P16P0	; Index 11
	dw Untitled_EffectBlock_P18P0P1	; Index 12
	dw Untitled_EffectBlock_P18P128P0	; Index 13
	dw Untitled_EffectBlock_P20P16P0	; Index 14
	dw Untitled_EffectBlock_P20P0P1	; Index 15
	dw Untitled_EffectBlock_P8	; Index 16
	dw Untitled_EffectBlock_P6P1	; Index 17
Untitled_DisarkPointerRegionEnd9

Untitled_EffectBlock_P8
	db 8
Untitled_EffectBlock_P4P0
	db 4, 0
Untitled_EffectBlock_P4P1
	db 4, 1
Untitled_EffectBlock_P4P2
	db 4, 2
Untitled_EffectBlock_P4P3
	db 4, 3
Untitled_EffectBlock_P6P1
	db 6, 1
Untitled_EffectBlock_P5P2P8
	db 5, 2, 8
Untitled_EffectBlock_P20P128P0
	db 20, 128, 0
Untitled_EffectBlock_P14P16P0
	db 14, 16, 0
Untitled_EffectBlock_P18P0P1
	db 18, 0, 1
Untitled_EffectBlock_P18P128P0
	db 18, 128, 0
Untitled_EffectBlock_P20P16P0
	db 20, 16, 0
Untitled_EffectBlock_P20P64P0
	db 20, 64, 0
Untitled_EffectBlock_P20P96P0
	db 20, 96, 0
Untitled_EffectBlock_P20P0P1
	db 20, 0, 1
Untitled_EffectBlock_P5P2P6P0
	db 5, 2, 6, 0
Untitled_EffectBlock_P5P2P6P1
	db 5, 2, 6, 1
Untitled_EffectBlock_P5P3P6P1
	db 5, 3, 6, 1

Untitled_DisarkByteRegionEnd0

; Subsong 0
; ----------------------
Untitled_Subsong0_DisarkByteRegionStart0
Untitled_Subsong0_Start
	db 2	; ReplayFrequency (0=12.5hz, 1=25, 2=50, 3=100, 4=150, 5=300).
	db 0	; Digichannel (0-2).
	db 1	; PSG count (>0).
	db 0	; Loop start index (>=0).
	db 15	; End index (>=0).
	db 6	; Initial speed (>=0).
	db 22	; Base note index (>=0).

Untitled_Subsong0_Linker
Untitled_Subsong0_DisarkPointerRegionStart1
; Position 0
Untitled_Subsong0_Linker_Loop
	dw Untitled_Subsong0_Track0
	dw Untitled_Subsong0_Track1
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock0

; Position 1
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 2
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 3
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock2

; Position 4
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 5
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 6
	dw Untitled_Subsong0_Track5
	dw Untitled_Subsong0_Track10
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock3

; Position 7
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock2

; Position 8
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_LinkerBlock1

; Position 9
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_Track4
	dw Untitled_Subsong0_Track3
	dw Untitled_Subsong0_LinkerBlock1

; Position 10
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 11
	dw Untitled_Subsong0_Track6
	dw Untitled_Subsong0_Track7
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 12
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_Track9
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 13
	dw Untitled_Subsong0_Track8
	dw Untitled_Subsong0_Track11
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 14
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

; Position 15
	dw Untitled_Subsong0_Track12
	dw Untitled_Subsong0_Track13
	dw Untitled_Subsong0_Track2
	dw Untitled_Subsong0_LinkerBlock1

Untitled_Subsong0_DisarkPointerRegionEnd1
	dw 0	; Loop.
Untitled_Subsong0_DisarkWordForceReference2
	dw Untitled_Subsong0_Linker_Loop

Untitled_Subsong0_LinkerBlock0
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference3
	dw Untitled_Subsong0_SpeedTrack0	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference4
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock1
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 0	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference5
	dw Untitled_Subsong0_SpeedTrack1	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference6
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock2
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db 2	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference7
	dw Untitled_Subsong0_SpeedTrack1	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference8
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.
Untitled_Subsong0_LinkerBlock3
	db 64	; Height.
	db 0	; Transposition 0.
	db 0	; Transposition 1.
	db -1	; Transposition 2.
Untitled_Subsong0_DisarkWordForceReference9
	dw Untitled_Subsong0_SpeedTrack1	; SpeedTrack address.
Untitled_Subsong0_DisarkWordForceReference10
	dw Untitled_Subsong0_EventTrack0	; EventTrack address.

Untitled_Subsong0_Track0
	db 128
	db 0	; New Instrument (0).
	db 61, 30	; Waits for 31 lines.

	db 211
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 7
	db 83
	db 1	; Index to an effect block.
	db 19
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 19
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 19
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 19
	db 19
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 7
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 7
	db 83
	db 1	; Index to an effect block.
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 71
	db 2	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 71
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track1
	db 128
	db 0	; New Instrument (0).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track2
	db 211
	db 7	; New Instrument (7).
	db 0	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 147
	db 5	; New Instrument (5).
	db 211
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 211
	db 6	; New Instrument (6).
	db 0	; Index to an effect block.
	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 147
	db 6	; New Instrument (6).
	db 147
	db 4	; New Instrument (4).
	db 147
	db 6	; New Instrument (6).
	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 147
	db 5	; New Instrument (5).
	db 211
	db 4	; New Instrument (4).
	db 1	; Index to an effect block.
	db 211
	db 6	; New Instrument (6).
	db 0	; Index to an effect block.
	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 7	; New Instrument (7).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 60	; Waits for 1 line.

	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 147
	db 6	; New Instrument (6).
	db 147
	db 4	; New Instrument (4).
	db 147
	db 6	; New Instrument (6).
	db 147
	db 4	; New Instrument (4).
	db 124	; No note, but effects.
	db 2	; Index to an effect block.
	db 147
	db 5	; New Instrument (5).
	db 60	; Waits for 1 line.

	db 147
	db 4	; New Instrument (4).
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track3
	db 211
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 7
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 7
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 7
	db 83
	db 1	; Index to an effect block.
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 19
	db 71
	db 0	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 71
	db 2	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 19
	db 7
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 71
	db 2	; Index to an effect block.
	db 83
	db 1	; Index to an effect block.
	db 71
	db 0	; Index to an effect block.
	db 19
	db 19
	db 7
	db 83
	db 1	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 7
	db 19
	db 19
	db 19
	db 71
	db 2	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 7
	db 19
	db 7
	db 19
	db 19
	db 7
	db 19
	db 19
	db 19
	db 7
	db 19
	db 19
	db 19
	db 71
	db 2	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 7
	db 19
	db 71
	db 2	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 71
	db 2	; Index to an effect block.
	db 83
	db 0	; Index to an effect block.
	db 19
	db 19
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track4
	db 235
	db 2	; New Instrument (2).
	db 6	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 36
	db 61, 6	; Waits for 7 lines.

	db 38
	db 61, 6	; Waits for 7 lines.

	db 31
	db 61, 14	; Waits for 15 lines.

	db 124	; No note, but effects.
	db 12	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track5
	db 208
	db 1	; New Instrument (1).
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 92
	db 1	; Index to an effect block.
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 16
	db 28
	db 16
	db 92
	db 1	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 28
	db 16
	db 28
	db 28
	db 16
	db 28
	db 16
	db 28
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 28
	db 16
	db 92
	db 1	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 16
	db 28
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 16
	db 92
	db 1	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 92
	db 1	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 28
	db 16
	db 28
	db 28
	db 16
	db 28
	db 16
	db 28
	db 28
	db 16
	db 28
	db 28
	db 28
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track6
	db 213
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 73
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 73
	db 2	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 73
	db 2	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 21
	db 9
	db 21
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 9
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 21
	db 9
	db 21
	db 21
	db 9
	db 85
	db 1	; Index to an effect block.
	db 73
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 9
	db 21
	db 21
	db 21
	db 9
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 21
	db 9
	db 21
	db 21
	db 9
	db 21
	db 9
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 9
	db 21
	db 21
	db 21
	db 9
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 21
	db 73
	db 2	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 21
	db 73
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 73
	db 0	; Index to an effect block.
	db 85
	db 1	; Index to an effect block.
	db 85
	db 0	; Index to an effect block.
	db 9
	db 21
	db 21
	db 9
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track7
	db 237
	db 2	; New Instrument (2).
	db 1	; Index to an effect block.
	db 61, 14	; Waits for 15 lines.

	db 38
	db 61, 6	; Waits for 7 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 33
	db 61, 9	; Waits for 10 lines.

	db 124	; No note, but effects.
	db 15	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track8
	db 223
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 31
	db 31
	db 83
	db 2	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 19
	db 31
	db 19
	db 31
	db 31
	db 19
	db 31
	db 83
	db 2	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 19
	db 31
	db 14
	db 26
	db 26
	db 26
	db 14
	db 26
	db 26
	db 14
	db 26
	db 26
	db 14
	db 26
	db 14
	db 26
	db 26
	db 14
	db 24
	db 12
	db 24
	db 24
	db 12
	db 24
	db 24
	db 12
	db 24
	db 12
	db 24
	db 24
	db 12
	db 24
	db 12
	db 24
	db 19
	db 95
	db 3	; Index to an effect block.
	db 95
	db 0	; Index to an effect block.
	db 19
	db 31
	db 31
	db 19
	db 31
	db 19
	db 31
	db 31
	db 19
	db 31
	db 19
	db 31
	db 83
	db 2	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track9
	db 239
	db 2	; New Instrument (2).
	db 9	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 47
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 109
	db 1	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 109
	db 3	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 61, 6	; Waits for 7 lines.

	db 43
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 43
	db 60	; Waits for 1 line.

	db 107
	db 1	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 55
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track10
	db 232
	db 3	; New Instrument (3).
	db 16	; Index to an effect block.
	db 124	; No note, but effects.
	db 0	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 40
	db 61, 6	; Waits for 7 lines.

	db 40
	db 60	; Waits for 1 line.

	db 166
	db 2	; New Instrument (2).
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 166
	db 3	; New Instrument (3).
	db 61, 6	; Waits for 7 lines.

	db 166
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 37
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 165
	db 3	; New Instrument (3).
	db 61, 6	; Waits for 7 lines.

	db 165
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 35
	db 60	; Waits for 1 line.

	db 124	; No note, but effects.
	db 10	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track11
	db 239
	db 2	; New Instrument (2).
	db 8	; Index to an effect block.
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 124	; No note, but effects.
	db 5	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 111
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 99
	db 11	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 109
	db 1	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 124	; No note, but effects.
	db 4	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 45
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 33
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 31
	db 60	; Waits for 1 line.

	db 104
	db 0	; Index to an effect block.
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 42
	db 60	; Waits for 1 line.

	db 107
	db 3	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 31
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 107
	db 1	; Index to an effect block.
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 43
	db 62 + 2 * 64	; Optimized wait for 4 lines.

	db 50
	db 62 + 0 * 64	; Optimized wait for 2 lines.

	db 43
	db 95
	db 3	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track12
	db 216
	db 1	; New Instrument (1).
	db 0	; Index to an effect block.
	db 24
	db 12
	db 24
	db 24
	db 12
	db 24
	db 12
	db 24
	db 12
	db 12
	db 24
	db 12
	db 24
	db 24
	db 12
	db 26
	db 26
	db 14
	db 26
	db 26
	db 14
	db 26
	db 14
	db 28
	db 14
	db 26
	db 26
	db 26
	db 14
	db 26
	db 78
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 16
	db 28
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 16
	db 28
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 16
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 16
	db 28
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 28
	db 80
	db 2	; Index to an effect block.
	db 92
	db 0	; Index to an effect block.
	db 16
	db 28
	db 80
	db 2	; Index to an effect block.
	db 28
	db 61, 127	; Waits for 128 lines.


Untitled_Subsong0_Track13
	db 228
	db 3	; New Instrument (3).
	db 7	; Index to an effect block.
	db 61, 6	; Waits for 7 lines.

	db 124	; No note, but effects.
	db 14	; Index to an effect block.
	db 62 + 3 * 64	; Optimized wait for 5 lines.

	db 228
	db 2	; New Instrument (2).
	db 16	; Index to an effect block.
	db 60	; Waits for 1 line.

	db 230
	db 3	; New Instrument (3).
	db 17	; Index to an effect block.
	db 61, 12	; Waits for 13 lines.

	db 166
	db 2	; New Instrument (2).
	db 60	; Waits for 1 line.

	db 28
	db 62 + 1 * 64	; Optimized wait for 3 lines.

	db 124	; No note, but effects.
	db 13	; Index to an effect block.
	db 61, 127	; Waits for 128 lines.


; The speed tracks
Untitled_Subsong0_SpeedTrack0
	db 12	; Value: 6.
	db 253	; Wait for 127 lines.
Untitled_Subsong0_SpeedTrack1
	db 255	; Wait for 128 lines.

; The event tracks
Untitled_Subsong0_EventTrack0
	db 255	; Wait for 128 lines.

Untitled_Subsong0_DisarkByteRegionEnd0
